language: rust
cache: cargo
rust:
  - stable
script:
  - nvm install --lts
  - cd love-letter-ui
  - npm install
  - npm run build
  # - npm run test
  - cd -
  - cargo build --verbose
  - cargo test --verbose
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: fUj7kn32h5cdoJIF9Plwmxp/XqQEUZGaoc5bj//mXSax3qBqOwj99kV4yIkBfk4ZOXH78s43Fp0UJDVlEtSI8rDDkwwJbk6um4UAYGIN9x8ylWy2Wc96W1WVl7ujHn92hnqM7BKOSfRx5ZwaTA8WCAurnMSKQepFI00UKWQOlOZD/Y+VunTG8P5lplSokQwcvaoinI29eTw5O7u11dnSIhyxysv6gAvDjkZnD0wng7B/Svg2uSXQ7wbNGIJLCPKpdftDL6Gsfn/E4e9gytynU7nmODE5rlIjEmr/GaZgAu1Lk2wT9Y0IEE8AKZxekGDYikijrKu6kqQDZqZewyeN3THCNTYfF1rs11MNbcNR2gaBz3HJfVK34YgGyJggvS1eWHOQRXArOD3Lhpobdu8hA4aYguNzRk/toZ6+bDs3TI4h3C48ZkilV7SLrP5Ney8ko1BQjLYP/En7vF2tlkzZ5z+up+FAnMOXeJUwy7wAk1/khcULxXOsKEwxeHSk90i3niYbEyLLdiysHroZEE6iW30ca7fxXEAoY1TNj13FtvUbMHdgGSUB4LvUBs8Si0kCYI7Snt8UdS78zVJQU6p+oaIC+yEUh2HLgKA7iR9sPeHwozobF2Fy80lQ51+eVi50Xqq2yVWUVjtQITZsv2yDfi0aFF7ksU/mLyiAXVruY40=
