[package]
name = "love-letter"
version = "0.1.0"
authors = ["Dan Knutson <dan.knutson@gmail.com>"]
edition = "2015"

[dependencies]
actix-web = "0.7"
serde_derive="1.0.79"
serde_json="1.0"
serde="1.0"